name: crud_todo_app
description: Create a To-do List app managing CRUD in Firebase and Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.0-dev.1
  flutter_hooks: ^0.17.0
  freezed_annotation: ^0.14.1
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.5
  flutter_slidable: ^0.6.0
  intl: ^0.17.0
  uuid: ^3.0.4
  flutter_emoji:
    git:
      url: git://github.com/cek-cek/flutter-emoji
  google_fonts: ^2.0.0
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.1.2
  build_runner: ^2.0.1
  freezed: ^0.14.1+3
  mocktail: ^0.1.4
  ## mockito: ^5.0.10
  remove_from_coverage: ^2.0.0

flutter:
  uses-material-design: true
